/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'camechis' at '9/28/13 9:34 PM' with Gradle 1.8
 *
 * @author camechis, @date 9/28/13 9:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
